cooksite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls', namespace='main')),
    path("recipes/", include('recipes.urls', namespace='recipes')),
    path('', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.custom_login, name='login'),
    # path('home', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    # path('create-post', views.create_post, name='create_post'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('home', views.homepages, name='homepages'),
    path('uploadrecipe', views.uploadrecipe, name='uploadrecipe'),
    path('personalrecs', views.personalrecs, name='personalrecs'),
    path('<int:pk>/details/', views.details, name='details'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# class Post(models.Model):
#     # Links each post to a specific user
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     title = models.CharField(max_length=200)
#     description = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.title + "\n" + self.description

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    # Links each post to a specific user
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='files/foodPics')
    likes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + "\n" + self.description

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
# from .models import Post


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        # Creating a new user
        model = User
        # assigning these fields to a certain user
        fields = ["username", "email", "password1", "password2"]


# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ["title", "description"]

recipes/forms.py
from django import forms
from .models import Post


class RecipePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'description', 'image']

main/views.py
from django.shortcuts import render, redirect, reverse
from .forms import RegisterForm  # , PostForm

from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
# from .models import Post
from recipes.views import homepages

# Create your views here.


def custom_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            url = reverse("recipes:homepages")
            return redirect(url)
        else:
            messages.error(
                request, 'Invalid login Credentials. Please try again')
    return render(request, 'registration/login.html')


# @login_required(login_url="/login")
# def home(request):
#     posts = Post.objects.all()

#     if request.method == "POST":
#         post_id = request.POST.get("post-id")
#         # get the post
#         post = Post.objects.filter(id=post_id).first()
#         if post and post.author == request.user:
#             post.delete()

#     return render(request, 'main/home.html', {"posts": posts})


# @login_required(login_url="/login")
# def create_post(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             # Commit is set to false because we don't want it added to the database until the username is included
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect("/home")
#     else:
#         form = PostForm()

#     return render(request, 'main/create_post.html', {"form": form})


def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            url = reverse('recipes:homepages')
            return redirect(url)
    else:
        form = RegisterForm()

    return render(request, 'registration/sign_up.html', {"form": form})

recipes/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Post
from .forms import RecipePostForm
from django.contrib.auth.decorators import login_required
# Create your views here.

#url = reverse('login')

def homepages(request):
    posts = Post.objects.all()
    return render(request, "recipes/homepage.html", {'posts':posts})


#@login_required('main/login')
def uploadrecipe(request):
    if request.method == 'POST':
        form = RecipePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('recipes:homepages')  # redirect to user's list of posts
    else:
        form = RecipePostForm()
    return render(request, 'recipes/createPost.html', {'form': form})

#@login_required('main/login')
def personalrecs(request):
    curr_user = request.user
    posts = Post.objects.filter(author_id=curr_user.id)
    #print(curr_user.id)
    if request.method == 'POST':
        post_id = request.POST.get("post-id")
        post = Post.objects.filter(id=post_id).first()
        if post and post.author == request.user:
            post.delete()

    return render(request, 'recipes/myrecipes.html', {'posts': posts})

def details(request, pk):
    post = get_object_or_404(Post, pk=pk)
    print(post.id)
    return render(request, "recipes/details.html", {"post":post})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <title>{% block title %}My site {% endblock %}</title>
</head>
<style>
    body{
        margin: 0;
        height: 100%;
    }
</style>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
    crossorigin="anonymous"></script>
</body>
</html>

recipes/templates/recipes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <title>{% block title %}My site {% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: brown;">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{%url 'recipes:homepages' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{%url 'recipes:uploadrecipe' %}" class="nav-link">Post A Recipe</a>
                    </li>
                    <li class="nav-item">
                        <a href="{%url 'recipes:personalrecs' %}" class="nav-link">My Posted Recipes</a>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    <span class="navbar-text">Logged in as {{user.username}} | </span>
                    <li class="nav-item">
                        <a href="/logout" class="nav-link">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a href="/settings" class="nav-link">Settings</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>

</html>

recipes/templates/recipes/createPost.html
{% extends 'recipes/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid" style="width: 100%; margin-left: -6vw;">
    <div class="row justify-content-center" style="width: 100%;">
        <div class="col">
            <img src="{% static '/GeneralImage/ahmadreza-rezaie-9x6QkgB722w-unsplash.jpg'%}" alt="pizza" width="800" height="700"
                style="object-fit:cover;">
        </div>
<div class="col mt-3">
    <h1>Enter Recipe Details</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
            <label for="id_title" class="form-label">Dish: </label>
            <input type="text" class="form-control" id="id_title" name="title" required>
            <br>
            <label for="id_description" class="form-label">Description: </label>
            <textarea class="form-control" id="id_description" name="description" required></textarea>
            <br>
            <label for="id_image" class="form-label">Image:</label>
            <input type="file" name="image" id="id_image" accept="image/*">
            <br>
            <button type="submit" class="btn mt-3" style="background-color: brown; color: white;">Submit New Post</button>
    </form>
        </div>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/details.html
{% extends 'recipes/base.html' %}
{% block title %} {% endblock %}
{%block content%}
<div class="container-fluid" style="width: 100%;">
    <div class="row justify-content-center" style="width: 100%;">

        <div class="col mt-3">
            <h1>{{post.title}}</h1>
            <h4>By {{post.author.get_username}}</h4>
            <p>{{post.created_at}}</p>
            <p>{{post.description}}</p>
        </div>
        <div class="col">
            <img class="mt-2 rounded mx-auto d-block" src="{{post.image.url}}" alt="Food Pics" width="700px" height="650px" />
        </div>

    </div>
</div>
{% endblock %}

recipes/templates/recipes/homepage.html
{% extends 'recipes/base.html' %}
{% block title %} Welcome Back! {% endblock %}
{% block content %}
<h3 class="text-center fs-3 mb-4">Your Feed</h3>
<div class="row gap-3 ">
    {%for post in posts %}
    <div class="col-md-3 card mx-2 mb-5" style="width: 18rem;">
        <img src="{{post.image.url}}" alt="Food Pics" class="card-img-top" height="280" style="margin-top: 10px;"/>
        <div class="card-body">       
            <h5 class="card-title"><a href="{% url 'recipes:details' pk=post.id %}" style="text-decoration: none; color: black;">{{post.title}}</a></h5>
            <p>Posted By: {{post.author.get_username}}</p>
        </div>
        
    </div>
    <!-- <p>{{post.description}}</p> -->
    {% endfor %}

</div>

{% endblock %}

recipes/templates/recipes/myrecipes.html
{% extends 'recipes/base.html' %}
{% block title %} Welcome Back! {% endblock %}
{% block content %}
<h3 class="text-center fs-3 mb-4">My Posts</h3>
<div class="row gap-3 ">
    {%for post in posts %}
    <div class="col-md-3 card mx-2 mb-5" style="width: 18rem;">
        <img src="{{post.image.url}}" alt="Food Pics" class="card-img-top" height="280" style="margin-top: 10px;" />
        <div class="card-body">
        <h5 class="card-title"><a href="{% url 'recipes:details' pk=post.id %}"
                                style="text-decoration: none; color: black;">{{post.title}}</a></h5>
<button type="button" class="btn " data-bs-toggle="modal" data-bs-target="#deleteModal" style="color: red;">
    Delete Post
</button>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this post?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" name="post-id" value="{{post.id}}">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

    </div>
    </div>
    {% endfor %}
</div>

{% endblock %}